/*
 * This file is generated by jOOQ.
 */
package uk.hotten.staffog.data.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import uk.hotten.staffog.data.jooq.tables.StaffogAppeal;
import uk.hotten.staffog.data.jooq.tables.StaffogAudit;
import uk.hotten.staffog.data.jooq.tables.StaffogBan;
import uk.hotten.staffog.data.jooq.tables.StaffogChatreport;
import uk.hotten.staffog.data.jooq.tables.StaffogHistory;
import uk.hotten.staffog.data.jooq.tables.StaffogKick;
import uk.hotten.staffog.data.jooq.tables.StaffogLinkcode;
import uk.hotten.staffog.data.jooq.tables.StaffogMute;
import uk.hotten.staffog.data.jooq.tables.StaffogReport;
import uk.hotten.staffog.data.jooq.tables.StaffogStaffip;
import uk.hotten.staffog.data.jooq.tables.StaffogTask;
import uk.hotten.staffog.data.jooq.tables.StaffogWeb;
import uk.hotten.staffog.data.jooq.tables.records.StaffogAppealRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogAuditRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogBanRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogChatreportRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogHistoryRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogKickRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogLinkcodeRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogMuteRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogReportRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogStaffipRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogTaskRecord;
import uk.hotten.staffog.data.jooq.tables.records.StaffogWebRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * staffog.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<StaffogAppealRecord> KEY_STAFFOG_APPEAL_PRIMARY = Internal.createUniqueKey(StaffogAppeal.STAFFOG_APPEAL, DSL.name("KEY_staffog_appeal_PRIMARY"), new TableField[] { StaffogAppeal.STAFFOG_APPEAL.ID }, true);
    public static final UniqueKey<StaffogAuditRecord> KEY_STAFFOG_AUDIT_PRIMARY = Internal.createUniqueKey(StaffogAudit.STAFFOG_AUDIT, DSL.name("KEY_staffog_audit_PRIMARY"), new TableField[] { StaffogAudit.STAFFOG_AUDIT.ID }, true);
    public static final UniqueKey<StaffogBanRecord> KEY_STAFFOG_BAN_PRIMARY = Internal.createUniqueKey(StaffogBan.STAFFOG_BAN, DSL.name("KEY_staffog_ban_PRIMARY"), new TableField[] { StaffogBan.STAFFOG_BAN.ID }, true);
    public static final UniqueKey<StaffogChatreportRecord> KEY_STAFFOG_CHATREPORT_PRIMARY = Internal.createUniqueKey(StaffogChatreport.STAFFOG_CHATREPORT, DSL.name("KEY_staffog_chatreport_PRIMARY"), new TableField[] { StaffogChatreport.STAFFOG_CHATREPORT.ID }, true);
    public static final UniqueKey<StaffogHistoryRecord> KEY_STAFFOG_HISTORY_PRIMARY = Internal.createUniqueKey(StaffogHistory.STAFFOG_HISTORY, DSL.name("KEY_staffog_history_PRIMARY"), new TableField[] { StaffogHistory.STAFFOG_HISTORY.ID }, true);
    public static final UniqueKey<StaffogKickRecord> KEY_STAFFOG_KICK_PRIMARY = Internal.createUniqueKey(StaffogKick.STAFFOG_KICK, DSL.name("KEY_staffog_kick_PRIMARY"), new TableField[] { StaffogKick.STAFFOG_KICK.ID }, true);
    public static final UniqueKey<StaffogLinkcodeRecord> KEY_STAFFOG_LINKCODE_UUID = Internal.createUniqueKey(StaffogLinkcode.STAFFOG_LINKCODE, DSL.name("KEY_staffog_linkcode_uuid"), new TableField[] { StaffogLinkcode.STAFFOG_LINKCODE.UUID }, true);
    public static final UniqueKey<StaffogMuteRecord> KEY_STAFFOG_MUTE_PRIMARY = Internal.createUniqueKey(StaffogMute.STAFFOG_MUTE, DSL.name("KEY_staffog_mute_PRIMARY"), new TableField[] { StaffogMute.STAFFOG_MUTE.ID }, true);
    public static final UniqueKey<StaffogReportRecord> KEY_STAFFOG_REPORT_PRIMARY = Internal.createUniqueKey(StaffogReport.STAFFOG_REPORT, DSL.name("KEY_staffog_report_PRIMARY"), new TableField[] { StaffogReport.STAFFOG_REPORT.ID }, true);
    public static final UniqueKey<StaffogStaffipRecord> KEY_STAFFOG_STAFFIP_PRIMARY = Internal.createUniqueKey(StaffogStaffip.STAFFOG_STAFFIP, DSL.name("KEY_staffog_staffip_PRIMARY"), new TableField[] { StaffogStaffip.STAFFOG_STAFFIP.ID }, true);
    public static final UniqueKey<StaffogTaskRecord> KEY_STAFFOG_TASK_PRIMARY = Internal.createUniqueKey(StaffogTask.STAFFOG_TASK, DSL.name("KEY_staffog_task_PRIMARY"), new TableField[] { StaffogTask.STAFFOG_TASK.ID }, true);
    public static final UniqueKey<StaffogWebRecord> KEY_STAFFOG_WEB_PRIMARY = Internal.createUniqueKey(StaffogWeb.STAFFOG_WEB, DSL.name("KEY_staffog_web_PRIMARY"), new TableField[] { StaffogWeb.STAFFOG_WEB.ID }, true);
    public static final UniqueKey<StaffogWebRecord> KEY_STAFFOG_WEB_USERNAME = Internal.createUniqueKey(StaffogWeb.STAFFOG_WEB, DSL.name("KEY_staffog_web_username"), new TableField[] { StaffogWeb.STAFFOG_WEB.USERNAME, StaffogWeb.STAFFOG_WEB.UUID }, true);
}
