reportWebAddress: "https://report.trueog.net"
appealWebAddress: "https://appeal.trueog.net"

sqlType: mariadb # Options: mariadb or mysql
sqlHost: localhost
sqlUsername: username
sqlPassword: password
sqlDatabase: staffog
sqlPort: 3306