name: Staff-OG
main: uk.hotten.staffog.StaffOGPlugin
version: 1.0-beta
api-version: 1.18
author: Gxorge
description: Punishment system for TrueOG.
depend: [Vault]

commands:
  linkpanel:
    description: Link your in-game account to the staff panel.
    permission: staffog.panelaccess
    usage: /<command>

  chatreport:
    description: Report a player for a chat offence.
    usage: /<command> <player> <reason>

  permban:
    description: Permanently ban a player.
    permission: staffog.command.permban
    usage: /<command> <player> <reason>

  tempban:
    description: Temporarily ban a player.
    permission: staffog.command.tempban
    usage: /<command> <player> <unit> <amount> <reason>

  unban:
    description: Unban a player.
    permission: staffog.command.unban
    usage: /<command> <player> <reason>

  permmute:
    description: Permanently mute a player.
    permission: staffog.command.permmute
    usage: /<command> <player> <reason>

  tempmute:
    description: Temporarily mute a player.
    permission: staffog.command.tempmute
    usage: /<command> <player> <unit> <amount> <reason>

  unmute:
    description: Unmute a player.
    permission: staffog.command.unmute
    usage: /<command> <player> <reason>

  kick:
    description: Kick a player.
    permission: staffog.command.kick
    usage: /<command> <player> [reason]