package uk.hotten.staffog.data.jooq.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import uk.hotten.staffog.data.jooq.tables.StaffogWeb;

/**
 * This class was generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffogWebRecord extends UpdatableRecordImpl<StaffogWebRecord> implements Record6<Integer, String, String, String, Boolean, Boolean> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>staffog.staffog_web.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>staffog.staffog_web.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>staffog.staffog_web.username</code>.
	 */
	public void setUsername(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>staffog.staffog_web.username</code>.
	 */
	public String getUsername() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>staffog.staffog_web.uuid</code>.
	 */
	public void setUuid(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>staffog.staffog_web.uuid</code>.
	 */
	public String getUuid() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>staffog.staffog_web.password</code>.
	 */
	public void setPassword(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>staffog.staffog_web.password</code>.
	 */
	public String getPassword() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>staffog.staffog_web.active</code>.
	 */
	public void setActive(Boolean value) {
		set(4, value);
	}

	/**
	 * Getter for <code>staffog.staffog_web.active</code>.
	 */
	public Boolean getActive() {
		return (Boolean) get(4);
	}

	/**
	 * Setter for <code>staffog.staffog_web.admin</code>.
	 */
	public void setAdmin(Boolean value) {
		set(5, value);
	}

	/**
	 * Getter for <code>staffog.staffog_web.admin</code>.
	 */
	public Boolean getAdmin() {
		return (Boolean) get(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row6<Integer, String, String, String, Boolean, Boolean> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	@Override
	public Row6<Integer, String, String, String, Boolean, Boolean> valuesRow() {
		return (Row6) super.valuesRow();
	}

	@Override
	public Field<Integer> field1() {
		return StaffogWeb.STAFFOG_WEB.ID;
	}

	@Override
	public Field<String> field2() {
		return StaffogWeb.STAFFOG_WEB.USERNAME;
	}

	@Override
	public Field<String> field3() {
		return StaffogWeb.STAFFOG_WEB.UUID;
	}

	@Override
	public Field<String> field4() {
		return StaffogWeb.STAFFOG_WEB.PASSWORD;
	}

	@Override
	public Field<Boolean> field5() {
		return StaffogWeb.STAFFOG_WEB.ACTIVE;
	}

	@Override
	public Field<Boolean> field6() {
		return StaffogWeb.STAFFOG_WEB.ADMIN;
	}

	@Override
	public Integer component1() {
		return getId();
	}

	@Override
	public String component2() {
		return getUsername();
	}

	@Override
	public String component3() {
		return getUuid();
	}

	@Override
	public String component4() {
		return getPassword();
	}

	@Override
	public Boolean component5() {
		return getActive();
	}

	@Override
	public Boolean component6() {
		return getAdmin();
	}

	@Override
	public Integer value1() {
		return getId();
	}

	@Override
	public String value2() {
		return getUsername();
	}

	@Override
	public String value3() {
		return getUuid();
	}

	@Override
	public String value4() {
		return getPassword();
	}

	@Override
	public Boolean value5() {
		return getActive();
	}

	@Override
	public Boolean value6() {
		return getAdmin();
	}

	@Override
	public StaffogWebRecord value1(Integer value) {
		setId(value);
		return this;
	}

	@Override
	public StaffogWebRecord value2(String value) {
		setUsername(value);
		return this;
	}

	@Override
	public StaffogWebRecord value3(String value) {
		setUuid(value);
		return this;
	}

	@Override
	public StaffogWebRecord value4(String value) {
		setPassword(value);
		return this;
	}

	@Override
	public StaffogWebRecord value5(Boolean value) {
		setActive(value);
		return this;
	}

	@Override
	public StaffogWebRecord value6(Boolean value) {
		setAdmin(value);
		return this;
	}

	@Override
	public StaffogWebRecord values(Integer value1, String value2, String value3, String value4, Boolean value5, Boolean value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StaffogWebRecord
	 */
	public StaffogWebRecord() {
		super(StaffogWeb.STAFFOG_WEB);
	}

	/**
	 * Create a detached, initialized StaffogWebRecord
	 */
	public StaffogWebRecord(Integer id, String username, String uuid, String password, Boolean active, Boolean admin) {

		super(StaffogWeb.STAFFOG_WEB);

		setId(id);
		setUsername(username);
		setUuid(uuid);
		setPassword(password);
		setActive(active);
		setAdmin(admin);
		resetChangedOnNotNull();

	}

}