package uk.hotten.staffog.data.jooq.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import uk.hotten.staffog.data.jooq.tables.StaffogKick;

/**
 * This class was generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffogKickRecord extends UpdatableRecordImpl<StaffogKickRecord> implements Record6<Long, String, String, String, String, Long> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>staffog.staffog_kick.id</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>staffog.staffog_kick.id</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>staffog.staffog_kick.uuid</code>.
	 */
	public void setUuid(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>staffog.staffog_kick.uuid</code>.
	 */
	public String getUuid() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>staffog.staffog_kick.reason</code>.
	 */
	public void setReason(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>staffog.staffog_kick.reason</code>.
	 */
	public String getReason() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>staffog.staffog_kick.by_uuid</code>.
	 */
	public void setByUuid(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>staffog.staffog_kick.by_uuid</code>.
	 */
	public String getByUuid() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>staffog.staffog_kick.by_name</code>.
	 */
	public void setByName(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>staffog.staffog_kick.by_name</code>.
	 */
	public String getByName() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>staffog.staffog_kick.time</code>.
	 */
	public void setTime(Long value) {
		set(5, value);
	}

	/**
	 * Getter for <code>staffog.staffog_kick.time</code>.
	 */
	public Long getTime() {
		return (Long) get(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row6<Long, String, String, String, String, Long> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	@Override
	public Row6<Long, String, String, String, String, Long> valuesRow() {
		return (Row6) super.valuesRow();
	}

	@Override
	public Field<Long> field1() {
		return StaffogKick.STAFFOG_KICK.ID;
	}

	@Override
	public Field<String> field2() {
		return StaffogKick.STAFFOG_KICK.UUID;
	}

	@Override
	public Field<String> field3() {
		return StaffogKick.STAFFOG_KICK.REASON;
	}

	@Override
	public Field<String> field4() {
		return StaffogKick.STAFFOG_KICK.BY_UUID;
	}

	@Override
	public Field<String> field5() {
		return StaffogKick.STAFFOG_KICK.BY_NAME;
	}

	@Override
	public Field<Long> field6() {
		return StaffogKick.STAFFOG_KICK.TIME;
	}

	@Override
	public Long component1() {
		return getId();
	}

	@Override
	public String component2() {
		return getUuid();
	}

	@Override
	public String component3() {
		return getReason();
	}

	@Override
	public String component4() {
		return getByUuid();
	}

	@Override
	public String component5() {
		return getByName();
	}

	@Override
	public Long component6() {
		return getTime();
	}

	@Override
	public Long value1() {
		return getId();
	}

	@Override
	public String value2() {
		return getUuid();
	}

	@Override
	public String value3() {
		return getReason();
	}

	@Override
	public String value4() {
		return getByUuid();
	}

	@Override
	public String value5() {
		return getByName();
	}

	@Override
	public Long value6() {
		return getTime();
	}

	@Override
	public StaffogKickRecord value1(Long value) {
		setId(value);
		return this;
	}

	@Override
	public StaffogKickRecord value2(String value) {
		setUuid(value);
		return this;
	}

	@Override
	public StaffogKickRecord value3(String value) {
		setReason(value);
		return this;
	}

	@Override
	public StaffogKickRecord value4(String value) {
		setByUuid(value);
		return this;
	}

	@Override
	public StaffogKickRecord value5(String value) {
		setByName(value);
		return this;
	}

	@Override
	public StaffogKickRecord value6(Long value) {
		setTime(value);
		return this;
	}

	@Override
	public StaffogKickRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StaffogKickRecord
	 */
	public StaffogKickRecord() {
		super(StaffogKick.STAFFOG_KICK);
	}

	/**
	 * Create a detached, initialized StaffogKickRecord
	 */
	public StaffogKickRecord(Long id, String uuid, String reason, String byUuid, String byName, Long time) {

		super(StaffogKick.STAFFOG_KICK);

		setId(id);
		setUuid(uuid);
		setReason(reason);
		setByUuid(byUuid);
		setByName(byName);
		setTime(time);
		resetChangedOnNotNull();

	}

}