/*
 * This file is generated by jOOQ.
 */
package uk.hotten.staffog.data.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import uk.hotten.staffog.data.jooq.tables.StaffogReport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffogReportRecord extends UpdatableRecordImpl<StaffogReportRecord> implements Record12<Integer, String, String, Long, String, String, Integer, Boolean, String, Boolean, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>staffog.staffog_report.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>staffog.staffog_report.uuid</code>.
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>staffog.staffog_report.by_uuid</code>.
     */
    public void setByUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.by_uuid</code>.
     */
    public String getByUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>staffog.staffog_report.time</code>.
     */
    public void setTime(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.time</code>.
     */
    public Long getTime() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>staffog.staffog_report.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>staffog.staffog_report.reason</code>.
     */
    public void setReason(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.reason</code>.
     */
    public String getReason() {
        return (String) get(5);
    }

    /**
     * Setter for <code>staffog.staffog_report.crid</code>.
     */
    public void setCrid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.crid</code>.
     */
    public Integer getCrid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>staffog.staffog_report.open</code>.
     */
    public void setOpen(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.open</code>.
     */
    public Boolean getOpen() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>staffog.staffog_report.assigned</code>.
     */
    public void setAssigned(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.assigned</code>.
     */
    public String getAssigned() {
        return (String) get(8);
    }

    /**
     * Setter for <code>staffog.staffog_report.verdict</code>.
     */
    public void setVerdict(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.verdict</code>.
     */
    public Boolean getVerdict() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>staffog.staffog_report.verdict_time</code>.
     */
    public void setVerdictTime(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.verdict_time</code>.
     */
    public Long getVerdictTime() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>staffog.staffog_report.comment</code>.
     */
    public void setComment(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>staffog.staffog_report.comment</code>.
     */
    public String getComment() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, Long, String, String, Integer, Boolean, String, Boolean, Long, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, Long, String, String, Integer, Boolean, String, Boolean, Long, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return StaffogReport.STAFFOG_REPORT.ID;
    }

    @Override
    public Field<String> field2() {
        return StaffogReport.STAFFOG_REPORT.UUID;
    }

    @Override
    public Field<String> field3() {
        return StaffogReport.STAFFOG_REPORT.BY_UUID;
    }

    @Override
    public Field<Long> field4() {
        return StaffogReport.STAFFOG_REPORT.TIME;
    }

    @Override
    public Field<String> field5() {
        return StaffogReport.STAFFOG_REPORT.TYPE;
    }

    @Override
    public Field<String> field6() {
        return StaffogReport.STAFFOG_REPORT.REASON;
    }

    @Override
    public Field<Integer> field7() {
        return StaffogReport.STAFFOG_REPORT.CRID;
    }

    @Override
    public Field<Boolean> field8() {
        return StaffogReport.STAFFOG_REPORT.OPEN;
    }

    @Override
    public Field<String> field9() {
        return StaffogReport.STAFFOG_REPORT.ASSIGNED;
    }

    @Override
    public Field<Boolean> field10() {
        return StaffogReport.STAFFOG_REPORT.VERDICT;
    }

    @Override
    public Field<Long> field11() {
        return StaffogReport.STAFFOG_REPORT.VERDICT_TIME;
    }

    @Override
    public Field<String> field12() {
        return StaffogReport.STAFFOG_REPORT.COMMENT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUuid();
    }

    @Override
    public String component3() {
        return getByUuid();
    }

    @Override
    public Long component4() {
        return getTime();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getReason();
    }

    @Override
    public Integer component7() {
        return getCrid();
    }

    @Override
    public Boolean component8() {
        return getOpen();
    }

    @Override
    public String component9() {
        return getAssigned();
    }

    @Override
    public Boolean component10() {
        return getVerdict();
    }

    @Override
    public Long component11() {
        return getVerdictTime();
    }

    @Override
    public String component12() {
        return getComment();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUuid();
    }

    @Override
    public String value3() {
        return getByUuid();
    }

    @Override
    public Long value4() {
        return getTime();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getReason();
    }

    @Override
    public Integer value7() {
        return getCrid();
    }

    @Override
    public Boolean value8() {
        return getOpen();
    }

    @Override
    public String value9() {
        return getAssigned();
    }

    @Override
    public Boolean value10() {
        return getVerdict();
    }

    @Override
    public Long value11() {
        return getVerdictTime();
    }

    @Override
    public String value12() {
        return getComment();
    }

    @Override
    public StaffogReportRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StaffogReportRecord value2(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public StaffogReportRecord value3(String value) {
        setByUuid(value);
        return this;
    }

    @Override
    public StaffogReportRecord value4(Long value) {
        setTime(value);
        return this;
    }

    @Override
    public StaffogReportRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public StaffogReportRecord value6(String value) {
        setReason(value);
        return this;
    }

    @Override
    public StaffogReportRecord value7(Integer value) {
        setCrid(value);
        return this;
    }

    @Override
    public StaffogReportRecord value8(Boolean value) {
        setOpen(value);
        return this;
    }

    @Override
    public StaffogReportRecord value9(String value) {
        setAssigned(value);
        return this;
    }

    @Override
    public StaffogReportRecord value10(Boolean value) {
        setVerdict(value);
        return this;
    }

    @Override
    public StaffogReportRecord value11(Long value) {
        setVerdictTime(value);
        return this;
    }

    @Override
    public StaffogReportRecord value12(String value) {
        setComment(value);
        return this;
    }

    @Override
    public StaffogReportRecord values(Integer value1, String value2, String value3, Long value4, String value5, String value6, Integer value7, Boolean value8, String value9, Boolean value10, Long value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffogReportRecord
     */
    public StaffogReportRecord() {
        super(StaffogReport.STAFFOG_REPORT);
    }

    /**
     * Create a detached, initialised StaffogReportRecord
     */
    public StaffogReportRecord(Integer id, String uuid, String byUuid, Long time, String type, String reason, Integer crid, Boolean open, String assigned, Boolean verdict, Long verdictTime, String comment) {
        super(StaffogReport.STAFFOG_REPORT);

        setId(id);
        setUuid(uuid);
        setByUuid(byUuid);
        setTime(time);
        setType(type);
        setReason(reason);
        setCrid(crid);
        setOpen(open);
        setAssigned(assigned);
        setVerdict(verdict);
        setVerdictTime(verdictTime);
        setComment(comment);
        resetChangedOnNotNull();
    }
}
