package uk.hotten.staffog.data.jooq.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import uk.hotten.staffog.data.jooq.tables.StaffogChatreport;

/**
 * This class was generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffogChatreportRecord extends UpdatableRecordImpl<StaffogChatreportRecord> implements Record5<Integer, String, String, Long, String> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>staffog.staffog_chatreport.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>staffog.staffog_chatreport.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>staffog.staffog_chatreport.uuid</code>.
	 */
	public void setUuid(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>staffog.staffog_chatreport.uuid</code>.
	 */
	public String getUuid() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>staffog.staffog_chatreport.by_uuid</code>.
	 */
	public void setByUuid(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>staffog.staffog_chatreport.by_uuid</code>.
	 */
	public String getByUuid() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>staffog.staffog_chatreport.time</code>.
	 */
	public void setTime(Long value) {
		set(3, value);
	}

	/**
	 * Getter for <code>staffog.staffog_chatreport.time</code>.
	 */
	public Long getTime() {
		return (Long) get(3);
	}

	/**
	 * Setter for <code>staffog.staffog_chatreport.messages</code>.
	 */
	public void setMessages(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>staffog.staffog_chatreport.messages</code>.
	 */
	public String getMessages() {
		return (String) get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row5<Integer, String, String, Long, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	@Override
	public Row5<Integer, String, String, Long, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	@Override
	public Field<Integer> field1() {
		return StaffogChatreport.STAFFOG_CHATREPORT.ID;
	}

	@Override
	public Field<String> field2() {
		return StaffogChatreport.STAFFOG_CHATREPORT.UUID;
	}

	@Override
	public Field<String> field3() {
		return StaffogChatreport.STAFFOG_CHATREPORT.BY_UUID;
	}

	@Override
	public Field<Long> field4() {
		return StaffogChatreport.STAFFOG_CHATREPORT.TIME;
	}

	@Override
	public Field<String> field5() {
		return StaffogChatreport.STAFFOG_CHATREPORT.MESSAGES;
	}

	@Override
	public Integer component1() {
		return getId();
	}

	@Override
	public String component2() {
		return getUuid();
	}

	@Override
	public String component3() {
		return getByUuid();
	}

	@Override
	public Long component4() {
		return getTime();
	}

	@Override
	public String component5() {
		return getMessages();
	}

	@Override
	public Integer value1() {
		return getId();
	}

	@Override
	public String value2() {
		return getUuid();
	}

	@Override
	public String value3() {
		return getByUuid();
	}

	@Override
	public Long value4() {
		return getTime();
	}

	@Override
	public String value5() {
		return getMessages();
	}

	@Override
	public StaffogChatreportRecord value1(Integer value) {
		setId(value);
		return this;
	}

	@Override
	public StaffogChatreportRecord value2(String value) {
		setUuid(value);
		return this;
	}

	@Override
	public StaffogChatreportRecord value3(String value) {
		setByUuid(value);
		return this;
	}

	@Override
	public StaffogChatreportRecord value4(Long value) {
		setTime(value);
		return this;
	}

	@Override
	public StaffogChatreportRecord value5(String value) {
		setMessages(value);
		return this;
	}

	@Override
	public StaffogChatreportRecord values(Integer value1, String value2, String value3, Long value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StaffogChatreportRecord
	 */
	public StaffogChatreportRecord() {
		super(StaffogChatreport.STAFFOG_CHATREPORT);
	}

	/**
	 * Create a detached, initialized StaffogChatreportRecord
	 */
	public StaffogChatreportRecord(Integer id, String uuid, String byUuid, Long time, String messages) {

		super(StaffogChatreport.STAFFOG_CHATREPORT);

		setId(id);
		setUuid(uuid);
		setByUuid(byUuid);
		setTime(time);
		setMessages(messages);
		resetChangedOnNotNull();

	}

}