package uk.hotten.staffog.data.jooq.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import uk.hotten.staffog.data.jooq.tables.StaffogReport;

/**
 * This class was generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffogReportRecord extends UpdatableRecordImpl<StaffogReportRecord> implements Record13<Integer, String, String, Long, String, String, String, Integer, Boolean, String, Boolean, Long, String> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>staffog.staffog_report.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>staffog.staffog_report.uuid</code>.
	 */
	public void setUuid(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.uuid</code>.
	 */
	public String getUuid() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>staffog.staffog_report.by_uuid</code>.
	 */
	public void setByUuid(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.by_uuid</code>.
	 */
	public String getByUuid() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>staffog.staffog_report.time</code>.
	 */
	public void setTime(Long value) {
		set(3, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.time</code>.
	 */
	public Long getTime() {
		return (Long) get(3);
	}

	/**
	 * Setter for <code>staffog.staffog_report.type</code>.
	 */
	public void setType(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.type</code>.
	 */
	public String getType() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>staffog.staffog_report.reason</code>.
	 */
	public void setReason(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.reason</code>.
	 */
	public String getReason() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>staffog.staffog_report.evidence</code>.
	 */
	public void setEvidence(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.evidence</code>.
	 */
	public String getEvidence() {
		return (String) get(6);
	}

	/**
	 * Setter for <code>staffog.staffog_report.crid</code>.
	 */
	public void setCrid(Integer value) {
		set(7, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.crid</code>.
	 */
	public Integer getCrid() {
		return (Integer) get(7);
	}

	/**
	 * Setter for <code>staffog.staffog_report.open</code>.
	 */
	public void setOpen(Boolean value) {
		set(8, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.open</code>.
	 */
	public Boolean getOpen() {
		return (Boolean) get(8);
	}

	/**
	 * Setter for <code>staffog.staffog_report.assigned</code>.
	 */
	public void setAssigned(String value) {
		set(9, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.assigned</code>.
	 */
	public String getAssigned() {
		return (String) get(9);
	}

	/**
	 * Setter for <code>staffog.staffog_report.verdict</code>.
	 */
	public void setVerdict(Boolean value) {
		set(10, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.verdict</code>.
	 */
	public Boolean getVerdict() {
		return (Boolean) get(10);
	}

	/**
	 * Setter for <code>staffog.staffog_report.verdict_time</code>.
	 */
	public void setVerdictTime(Long value) {
		set(11, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.verdict_time</code>.
	 */
	public Long getVerdictTime() {
		return (Long) get(11);
	}

	/**
	 * Setter for <code>staffog.staffog_report.comment</code>.
	 */
	public void setComment(String value) {
		set(12, value);
	}

	/**
	 * Getter for <code>staffog.staffog_report.comment</code>.
	 */
	public String getComment() {
		return (String) get(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row13<Integer, String, String, Long, String, String, String, Integer, Boolean, String, Boolean, Long, String> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	@Override
	public Row13<Integer, String, String, Long, String, String, String, Integer, Boolean, String, Boolean, Long, String> valuesRow() {
		return (Row13) super.valuesRow();
	}

	@Override
	public Field<Integer> field1() {
		return StaffogReport.STAFFOG_REPORT.ID;
	}

	@Override
	public Field<String> field2() {
		return StaffogReport.STAFFOG_REPORT.UUID;
	}

	@Override
	public Field<String> field3() {
		return StaffogReport.STAFFOG_REPORT.BY_UUID;
	}

	@Override
	public Field<Long> field4() {
		return StaffogReport.STAFFOG_REPORT.TIME;
	}

	@Override
	public Field<String> field5() {
		return StaffogReport.STAFFOG_REPORT.TYPE;
	}

	@Override
	public Field<String> field6() {
		return StaffogReport.STAFFOG_REPORT.REASON;
	}

	@Override
	public Field<String> field7() {
		return StaffogReport.STAFFOG_REPORT.EVIDENCE;
	}

	@Override
	public Field<Integer> field8() {
		return StaffogReport.STAFFOG_REPORT.CRID;
	}

	@Override
	public Field<Boolean> field9() {
		return StaffogReport.STAFFOG_REPORT.OPEN;
	}

	@Override
	public Field<String> field10() {
		return StaffogReport.STAFFOG_REPORT.ASSIGNED;
	}

	@Override
	public Field<Boolean> field11() {
		return StaffogReport.STAFFOG_REPORT.VERDICT;
	}

	@Override
	public Field<Long> field12() {
		return StaffogReport.STAFFOG_REPORT.VERDICT_TIME;
	}

	@Override
	public Field<String> field13() {
		return StaffogReport.STAFFOG_REPORT.COMMENT;
	}

	@Override
	public Integer component1() {
		return getId();
	}

	@Override
	public String component2() {
		return getUuid();
	}

	@Override
	public String component3() {
		return getByUuid();
	}

	@Override
	public Long component4() {
		return getTime();
	}

	@Override
	public String component5() {
		return getType();
	}

	@Override
	public String component6() {
		return getReason();
	}

	@Override
	public String component7() {
		return getEvidence();
	}

	@Override
	public Integer component8() {
		return getCrid();
	}

	@Override
	public Boolean component9() {
		return getOpen();
	}

	@Override
	public String component10() {
		return getAssigned();
	}

	@Override
	public Boolean component11() {
		return getVerdict();
	}

	@Override
	public Long component12() {
		return getVerdictTime();
	}

	@Override
	public String component13() {
		return getComment();
	}

	@Override
	public Integer value1() {
		return getId();
	}

	@Override
	public String value2() {
		return getUuid();
	}

	@Override
	public String value3() {
		return getByUuid();
	}

	@Override
	public Long value4() {
		return getTime();
	}

	@Override
	public String value5() {
		return getType();
	}

	@Override
	public String value6() {
		return getReason();
	}

	@Override
	public String value7() {
		return getEvidence();
	}

	@Override
	public Integer value8() {
		return getCrid();
	}

	@Override
	public Boolean value9() {
		return getOpen();
	}

	@Override
	public String value10() {
		return getAssigned();
	}

	@Override
	public Boolean value11() {
		return getVerdict();
	}

	@Override
	public Long value12() {
		return getVerdictTime();
	}

	@Override
	public String value13() {
		return getComment();
	}

	@Override
	public StaffogReportRecord value1(Integer value) {
		setId(value);
		return this;
	}

	@Override
	public StaffogReportRecord value2(String value) {
		setUuid(value);
		return this;
	}

	@Override
	public StaffogReportRecord value3(String value) {
		setByUuid(value);
		return this;
	}

	@Override
	public StaffogReportRecord value4(Long value) {
		setTime(value);
		return this;
	}

	@Override
	public StaffogReportRecord value5(String value) {
		setType(value);
		return this;
	}

	@Override
	public StaffogReportRecord value6(String value) {
		setReason(value);
		return this;
	}

	@Override
	public StaffogReportRecord value7(String value) {
		setEvidence(value);
		return this;
	}

	@Override
	public StaffogReportRecord value8(Integer value) {
		setCrid(value);
		return this;
	}

	@Override
	public StaffogReportRecord value9(Boolean value) {
		setOpen(value);
		return this;
	}

	@Override
	public StaffogReportRecord value10(String value) {
		setAssigned(value);
		return this;
	}

	@Override
	public StaffogReportRecord value11(Boolean value) {
		setVerdict(value);
		return this;
	}

	@Override
	public StaffogReportRecord value12(Long value) {
		setVerdictTime(value);
		return this;
	}

	@Override
	public StaffogReportRecord value13(String value) {
		setComment(value);
		return this;
	}

	@Override
	public StaffogReportRecord values(Integer value1, String value2, String value3, Long value4, String value5, String value6, String value7, Integer value8, Boolean value9, String value10, Boolean value11, Long value12, String value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StaffogReportRecord
	 */
	public StaffogReportRecord() {
		super(StaffogReport.STAFFOG_REPORT);
	}

	/**
	 * Create a detached, initialized StaffogReportRecord
	 */
	public StaffogReportRecord(Integer id, String uuid, String byUuid, Long time, String type, String reason, String evidence, Integer crid, Boolean open, String assigned, Boolean verdict, Long verdictTime, String comment) {

		super(StaffogReport.STAFFOG_REPORT);

		setId(id);
		setUuid(uuid);
		setByUuid(byUuid);
		setTime(time);
		setType(type);
		setReason(reason);
		setEvidence(evidence);
		setCrid(crid);
		setOpen(open);
		setAssigned(assigned);
		setVerdict(verdict);
		setVerdictTime(verdictTime);
		setComment(comment);
		resetChangedOnNotNull();

	}

}