/*
 * This file is generated by jOOQ.
 */
package uk.hotten.staffog.data.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import uk.hotten.staffog.data.jooq.tables.StaffogStaffip;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffogStaffipRecord extends UpdatableRecordImpl<StaffogStaffipRecord> implements Record7<Integer, String, String, Boolean, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>staffog.staffog_staffip.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>staffog.staffog_staffip.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>staffog.staffog_staffip.ip</code>.
     */
    public void setIp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>staffog.staffog_staffip.ip</code>.
     */
    public String getIp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>staffog.staffog_staffip.uuid</code>.
     */
    public void setUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>staffog.staffog_staffip.uuid</code>.
     */
    public String getUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>staffog.staffog_staffip.initial</code>.
     */
    public void setInitial(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>staffog.staffog_staffip.initial</code>.
     */
    public Boolean getInitial() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>staffog.staffog_staffip.panel_acknowledged</code>.
     */
    public void setPanelAcknowledged(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>staffog.staffog_staffip.panel_acknowledged</code>.
     */
    public Boolean getPanelAcknowledged() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>staffog.staffog_staffip.panel_verified</code>.
     */
    public void setPanelVerified(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>staffog.staffog_staffip.panel_verified</code>.
     */
    public Boolean getPanelVerified() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>staffog.staffog_staffip.game_verified</code>.
     */
    public void setGameVerified(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>staffog.staffog_staffip.game_verified</code>.
     */
    public Boolean getGameVerified() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Boolean, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, Boolean, Boolean, Boolean, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return StaffogStaffip.STAFFOG_STAFFIP.ID;
    }

    @Override
    public Field<String> field2() {
        return StaffogStaffip.STAFFOG_STAFFIP.IP;
    }

    @Override
    public Field<String> field3() {
        return StaffogStaffip.STAFFOG_STAFFIP.UUID;
    }

    @Override
    public Field<Boolean> field4() {
        return StaffogStaffip.STAFFOG_STAFFIP.INITIAL;
    }

    @Override
    public Field<Boolean> field5() {
        return StaffogStaffip.STAFFOG_STAFFIP.PANEL_ACKNOWLEDGED;
    }

    @Override
    public Field<Boolean> field6() {
        return StaffogStaffip.STAFFOG_STAFFIP.PANEL_VERIFIED;
    }

    @Override
    public Field<Boolean> field7() {
        return StaffogStaffip.STAFFOG_STAFFIP.GAME_VERIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getIp();
    }

    @Override
    public String component3() {
        return getUuid();
    }

    @Override
    public Boolean component4() {
        return getInitial();
    }

    @Override
    public Boolean component5() {
        return getPanelAcknowledged();
    }

    @Override
    public Boolean component6() {
        return getPanelVerified();
    }

    @Override
    public Boolean component7() {
        return getGameVerified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getIp();
    }

    @Override
    public String value3() {
        return getUuid();
    }

    @Override
    public Boolean value4() {
        return getInitial();
    }

    @Override
    public Boolean value5() {
        return getPanelAcknowledged();
    }

    @Override
    public Boolean value6() {
        return getPanelVerified();
    }

    @Override
    public Boolean value7() {
        return getGameVerified();
    }

    @Override
    public StaffogStaffipRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StaffogStaffipRecord value2(String value) {
        setIp(value);
        return this;
    }

    @Override
    public StaffogStaffipRecord value3(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public StaffogStaffipRecord value4(Boolean value) {
        setInitial(value);
        return this;
    }

    @Override
    public StaffogStaffipRecord value5(Boolean value) {
        setPanelAcknowledged(value);
        return this;
    }

    @Override
    public StaffogStaffipRecord value6(Boolean value) {
        setPanelVerified(value);
        return this;
    }

    @Override
    public StaffogStaffipRecord value7(Boolean value) {
        setGameVerified(value);
        return this;
    }

    @Override
    public StaffogStaffipRecord values(Integer value1, String value2, String value3, Boolean value4, Boolean value5, Boolean value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffogStaffipRecord
     */
    public StaffogStaffipRecord() {
        super(StaffogStaffip.STAFFOG_STAFFIP);
    }

    /**
     * Create a detached, initialised StaffogStaffipRecord
     */
    public StaffogStaffipRecord(Integer id, String ip, String uuid, Boolean initial, Boolean panelAcknowledged, Boolean panelVerified, Boolean gameVerified) {
        super(StaffogStaffip.STAFFOG_STAFFIP);

        setId(id);
        setIp(ip);
        setUuid(uuid);
        setInitial(initial);
        setPanelAcknowledged(panelAcknowledged);
        setPanelVerified(panelVerified);
        setGameVerified(gameVerified);
        resetChangedOnNotNull();
    }
}
