/*
 * This file is generated by jOOQ.
 */
package uk.hotten.staffog.data.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import uk.hotten.staffog.data.jooq.tables.StaffogBan;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffogBanRecord extends UpdatableRecordImpl<StaffogBanRecord> implements Record12<Long, String, String, String, String, String, String, String, Long, Long, Long, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>staffog.staffog_ban.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>staffog.staffog_ban.uuid</code>.
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>staffog.staffog_ban.reason</code>.
     */
    public void setReason(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.reason</code>.
     */
    public String getReason() {
        return (String) get(2);
    }

    /**
     * Setter for <code>staffog.staffog_ban.by_uuid</code>.
     */
    public void setByUuid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.by_uuid</code>.
     */
    public String getByUuid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>staffog.staffog_ban.by_name</code>.
     */
    public void setByName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.by_name</code>.
     */
    public String getByName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>staffog.staffog_ban.removed_uuid</code>.
     */
    public void setRemovedUuid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.removed_uuid</code>.
     */
    public String getRemovedUuid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>staffog.staffog_ban.removed_name</code>.
     */
    public void setRemovedName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.removed_name</code>.
     */
    public String getRemovedName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>staffog.staffog_ban.removed_reason</code>.
     */
    public void setRemovedReason(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.removed_reason</code>.
     */
    public String getRemovedReason() {
        return (String) get(7);
    }

    /**
     * Setter for <code>staffog.staffog_ban.removed_time</code>.
     */
    public void setRemovedTime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.removed_time</code>.
     */
    public Long getRemovedTime() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>staffog.staffog_ban.time</code>.
     */
    public void setTime(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.time</code>.
     */
    public Long getTime() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>staffog.staffog_ban.until</code>.
     */
    public void setUntil(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.until</code>.
     */
    public Long getUntil() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>staffog.staffog_ban.active</code>.
     */
    public void setActive(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>staffog.staffog_ban.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, String, String, String, Long, Long, Long, Boolean> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, String, String, String, String, String, Long, Long, Long, Boolean> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StaffogBan.STAFFOG_BAN.ID;
    }

    @Override
    public Field<String> field2() {
        return StaffogBan.STAFFOG_BAN.UUID;
    }

    @Override
    public Field<String> field3() {
        return StaffogBan.STAFFOG_BAN.REASON;
    }

    @Override
    public Field<String> field4() {
        return StaffogBan.STAFFOG_BAN.BY_UUID;
    }

    @Override
    public Field<String> field5() {
        return StaffogBan.STAFFOG_BAN.BY_NAME;
    }

    @Override
    public Field<String> field6() {
        return StaffogBan.STAFFOG_BAN.REMOVED_UUID;
    }

    @Override
    public Field<String> field7() {
        return StaffogBan.STAFFOG_BAN.REMOVED_NAME;
    }

    @Override
    public Field<String> field8() {
        return StaffogBan.STAFFOG_BAN.REMOVED_REASON;
    }

    @Override
    public Field<Long> field9() {
        return StaffogBan.STAFFOG_BAN.REMOVED_TIME;
    }

    @Override
    public Field<Long> field10() {
        return StaffogBan.STAFFOG_BAN.TIME;
    }

    @Override
    public Field<Long> field11() {
        return StaffogBan.STAFFOG_BAN.UNTIL;
    }

    @Override
    public Field<Boolean> field12() {
        return StaffogBan.STAFFOG_BAN.ACTIVE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUuid();
    }

    @Override
    public String component3() {
        return getReason();
    }

    @Override
    public String component4() {
        return getByUuid();
    }

    @Override
    public String component5() {
        return getByName();
    }

    @Override
    public String component6() {
        return getRemovedUuid();
    }

    @Override
    public String component7() {
        return getRemovedName();
    }

    @Override
    public String component8() {
        return getRemovedReason();
    }

    @Override
    public Long component9() {
        return getRemovedTime();
    }

    @Override
    public Long component10() {
        return getTime();
    }

    @Override
    public Long component11() {
        return getUntil();
    }

    @Override
    public Boolean component12() {
        return getActive();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUuid();
    }

    @Override
    public String value3() {
        return getReason();
    }

    @Override
    public String value4() {
        return getByUuid();
    }

    @Override
    public String value5() {
        return getByName();
    }

    @Override
    public String value6() {
        return getRemovedUuid();
    }

    @Override
    public String value7() {
        return getRemovedName();
    }

    @Override
    public String value8() {
        return getRemovedReason();
    }

    @Override
    public Long value9() {
        return getRemovedTime();
    }

    @Override
    public Long value10() {
        return getTime();
    }

    @Override
    public Long value11() {
        return getUntil();
    }

    @Override
    public Boolean value12() {
        return getActive();
    }

    @Override
    public StaffogBanRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StaffogBanRecord value2(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public StaffogBanRecord value3(String value) {
        setReason(value);
        return this;
    }

    @Override
    public StaffogBanRecord value4(String value) {
        setByUuid(value);
        return this;
    }

    @Override
    public StaffogBanRecord value5(String value) {
        setByName(value);
        return this;
    }

    @Override
    public StaffogBanRecord value6(String value) {
        setRemovedUuid(value);
        return this;
    }

    @Override
    public StaffogBanRecord value7(String value) {
        setRemovedName(value);
        return this;
    }

    @Override
    public StaffogBanRecord value8(String value) {
        setRemovedReason(value);
        return this;
    }

    @Override
    public StaffogBanRecord value9(Long value) {
        setRemovedTime(value);
        return this;
    }

    @Override
    public StaffogBanRecord value10(Long value) {
        setTime(value);
        return this;
    }

    @Override
    public StaffogBanRecord value11(Long value) {
        setUntil(value);
        return this;
    }

    @Override
    public StaffogBanRecord value12(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public StaffogBanRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Long value9, Long value10, Long value11, Boolean value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffogBanRecord
     */
    public StaffogBanRecord() {
        super(StaffogBan.STAFFOG_BAN);
    }

    /**
     * Create a detached, initialised StaffogBanRecord
     */
    public StaffogBanRecord(Long id, String uuid, String reason, String byUuid, String byName, String removedUuid, String removedName, String removedReason, Long removedTime, Long time, Long until, Boolean active) {
        super(StaffogBan.STAFFOG_BAN);

        setId(id);
        setUuid(uuid);
        setReason(reason);
        setByUuid(byUuid);
        setByName(byName);
        setRemovedUuid(removedUuid);
        setRemovedName(removedName);
        setRemovedReason(removedReason);
        setRemovedTime(removedTime);
        setTime(time);
        setUntil(until);
        setActive(active);
        resetChangedOnNotNull();
    }
}
