/*
 * This file is generated by jOOQ.
 */
package uk.hotten.staffog.data.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import uk.hotten.staffog.data.jooq.tables.StaffogStat;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffogStatRecord extends TableRecordImpl<StaffogStatRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>staffog.staffog_stat.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>staffog.staffog_stat.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>staffog.staffog_stat.stat</code>.
     */
    public void setStat(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>staffog.staffog_stat.stat</code>.
     */
    public String getStat() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return StaffogStat.STAFFOG_STAT.NAME;
    }

    @Override
    public Field<String> field2() {
        return StaffogStat.STAFFOG_STAT.STAT;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getStat();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getStat();
    }

    @Override
    public StaffogStatRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public StaffogStatRecord value2(String value) {
        setStat(value);
        return this;
    }

    @Override
    public StaffogStatRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffogStatRecord
     */
    public StaffogStatRecord() {
        super(StaffogStat.STAFFOG_STAT);
    }

    /**
     * Create a detached, initialised StaffogStatRecord
     */
    public StaffogStatRecord(String name, String stat) {
        super(StaffogStat.STAFFOG_STAT);

        setName(name);
        setStat(stat);
        resetChangedOnNotNull();
    }
}
